name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  list-dpds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List DPDs
        run: |
          DPDS=$(ls -m ${{ github.workspace }}/src/main/resources/**/*.json | sed 's/, /",/g' | tr '\n' '"')
          echo 'dpds=[$DPDS]'
          echo 'dpds=[$DPDS]' >> "$GITHUB_OUTPUT"

  verify-json-validation:
    runs-on: ubuntu-latest
    needs: list-dpds

    env:
      SCHEMA_LOCATION: "${{ github.workspace }}/schema.json"

    steps:
      - uses: actions/checkout@v4

      - name: Download schema
        run: curl https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/main/schema/data-product-definition-schema.json -o $SCHEMA_LOCATION

      - name: Validate JSON
        id: validate-json
        uses: ammarlakis/action-ajv@master
        with:
          schema: ${{ env.SCHEMA_LOCATION }}
          data: ${{ matrix.dpd }}
          allErrors: true
          verbose: true

      - name: Fail if invalid files found
        if: ${{ steps.validate-json.outputs.valid }}
        run: |
          echo "${{ steps.validate-json.outputs.valid }}"
          if [[ ${{ steps.validate-json.outputs.valid }} ]]; then exit 0; else exit 1; fi
