name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize



jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    env:
      SCHEMA_LOCATION: "${{ github.workspace }}/schema.json"
    steps:
      - uses: actions/checkout@v4

      - name: Download schema
        run: curl https://raw.githubusercontent.com/ministryofjustice/hmpps-digital-prison-reporting-data-product-definitions-schema/main/schema/data-product-definition-schema.json -o $SCHEMA_LOCATION

      - name: Validate JSON
        id: validate-json
        uses: ammarlakis/action-ajv@master
        with:
          schema: ${{ env.SCHEMA_LOCATION }}
          data: "${{ github.workspace }}/src/main/resources/**/*.json"
          allErrors: true

      - name: Fail if invalid files found
        if: ${{ steps.validate-json.outputs.valid }}
        run: |
          echo "${{ steps.validate-json.outputs.valid }}"
          if [[ ${{ steps.validate-json.outputs.valid }} ]]; then exit 0; else exit 1; fi