name: Publish

on:
  workflow_dispatch:
    inputs:
      deployEnv:
        description: 'The environment to deploy DPDs to'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - preprod
          - prod
      deployFolder:
        description: 'The subfolder to deploy (e.g. dps/activities)'
        required: true
        default: orphanage
        type: text
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  tag:
    name: Tag commit
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
          with_initial_version: true
          initial_version: v1.0.0

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'


  publish-dpds:
    name: Publish DPDs to ${{ inputs.deployEnv || 'dev' }} env
    environment: ${{ inputs.deployEnv || 'dev' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/dpr-dpd-table-github-deploy-role"
          role-session-name: githubactionsrolesession
          aws-region: "eu-west-2"

      - name: Publish to DynamoDB
        shell: bash
        run: |
          DPD_PATH="definitions/prisons/${{ inputs.deployFolder || 'orphanage' }}"
          DPD_FOLDER="$GITHUB_WORKSPACE/src/main/resources/${{ inputs.deployEnv || 'dev' }}/$DPD_PATH/"
          echo "Searching folder: $DPD_FOLDER"
          echo "Path: $DPD_PATH"
         
          DPDs=($(find $DPD_FOLDER -name "*.json"))
          
          mkdir $GITHUB_WORKSPACE/temp
          
          for FILE_PATH in "${DPDs[@]}"
          do
            FILENAME=$(basename $FILE_PATH)
            DPD_ID=$(jq -r '.id' $FILE_PATH)
          
            echo "File: $FILENAME ID: $DPD_ID"
          
            JSON_TEXT=$(jq -Rsc <$FILE_PATH)
            JSON_TEXT=$(echo "$JSON_TEXT" | sed 's/\/\*[^*]+\*\///')
            JSON_TEXT=$(echo "$JSON_TEXT" | sed 's/^"//')
            JSON_TEXT=$(echo "$JSON_TEXT" | sed 's/"$//')

            echo "{ \"data-product-id\": { \"S\": \"$DPD_ID\" }, \"category\": { \"S\": \"$DPD_PATH\" }, \"definition\": { \"S\": \"$JSON_TEXT\" }, \"filename\": { \"S\": \"$FILENAME\" } }" > $GITHUB_WORKSPACE/temp/$DPD_ID.json
          
            aws dynamodb put-item \
              --table-name dpr-data-product-definition \
              --item file://$GITHUB_WORKSPACE/temp/$DPD_ID.json
          
            rm -f file://$GITHUB_WORKSPACE/temp/$DPD_ID.json
            
          done
